apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: job-board-portal
spec:
  type: NodePort
  selector:
    app: job-board
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 30080
